# Generated by Django 4.2.1 on 2024-01-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200, unique=True)),
                ('overview', models.TextField()),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=250)),
                ('patient_age', models.TextField()),
                ('patient_address', models.TextField()),
                ('patient_zipcode', models.CharField(max_length=20)),
                ('patient_country', models.CharField(max_length=200)),
                ('patient_mobile', models.CharField(max_length=15)),
                ('patient_email', models.CharField(max_length=200)),
                ('patient_password', models.CharField(max_length=250)),
            ],
        ),
    ]
