# Generated by Django 4.2.1 on 2024-02-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date_booked']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department_name']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['personal_details']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['personal_details']},
        ),
        migrations.AlterModelOptions(
            name='personaldetail',
            options={'ordering': ['name']},
        ),
    ]
