# Generated by Django 4.2.1 on 2024-02-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_patients_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='patient_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
    ]
