# Generated by Django 4.2.1 on 2024-02-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_booking_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attended',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
