# Generated by Django 4.2.1 on 2024-02-01 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_patients_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField()),
                ('education', models.CharField()),
                ('speciality', models.CharField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_age', models.TextField()),
                ('password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('address', models.TextField()),
                ('zipcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
        migrations.AddField(
            model_name='patient',
            name='personal_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.personaldetail'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='personal_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.personaldetail'),
        ),
    ]
