# Generated by Django 4.2.1 on 2024-02-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_set_default_values'),
        ('home', '0003_set_default_doctor_number'),
    ]

    operations = [
    ]
