# Generated by Django 4.2.1 on 2024-02-16 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20240214_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_Number',
            field=models.CharField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField()),
                ('dose', models.CharField()),
                ('frequency', models.CharField()),
                ('route', models.CharField()),
                ('quantity', models.CharField()),
                ('comment', models.TextField(null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.booking')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField()),
                ('weight', models.CharField()),
                ('bp', models.CharField()),
                ('pulse', models.CharField()),
                ('saturation', models.CharField()),
                ('temperature', models.CharField()),
                ('allergy', models.TextField()),
                ('medical_history', models.TextField()),
                ('medications', models.TextField()),
                ('present_complaints', models.TextField()),
                ('physical_examination', models.TextField(null=True)),
                ('diagnosis', models.TextField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.booking')),
            ],
        ),
    ]
