# Generated by Django 4.2.1 on 2024-02-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_patient_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
