# Generated by Django 4.2.1 on 2024-02-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_personaldetail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(default=12, upload_to='doctors'),
            preserve_default=False,
        ),
    ]
