# Generated by Django 4.2.1 on 2024-02-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_medicalreport_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='report',
            field=models.FileField(blank=True, upload_to='medical_reports'),
        ),
    ]
